### ISSUE TITLE
Tag container checkboxes not working

### ISSUE THREAD

**Issue by dollajas** [AnKingMed/anking_notes_addon#1]
Video displaying issue here: https://imgur.com/a/yyTxELa

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49

**Comment by RisingOrange** [comment]
Thanks for reporting! I noticed the issue earlier today and fixed it (86464b2402c6c18620e3c35c007b722f5f421050). The version with the fix was not yet uploaded to Ankiweb but it will be soon.

**Comment by dollajas** [comment]
fantastic, thanks!

**Comment by dollajas** [comment]
@RisingOrange hi, this issue is still persisting on my end, I have received the update the same day you pushed it out and restarted Anki

**Comment by RisingOrange** [comment]
Do other checkboxes work for you (for example the ones in the Fields section)? If not, try deleting the add-on and getting it from AnkiWeb again: https://ankiweb.net/shared/info/952691989 
Your settings will not get deleted by doing this.
If that doesn't help please send me the front card template of the note type you experience the problem with.
(From the main window go to Tools -> Manage note types -> Choose the note type -> Cards -> Front Template)

**Comment by dollajas** [comment]
@RisingOrange deleted and reimported and the issue persists. Other sections like fields are working fine. I tried changing tag container to block manually as in previous versions of the note type, but it displayed tags on the front and back of the card - so I wonder if that may be part of the issue

Here is the front template:

<div id="text">{{cloze:Text}}</div>

<br>






<script>
// ############## USER CONFIGURATION START ##############
// Auto flip to back when One by one mode.
var autoflip = false 

// Timer config (timer length, timer finished message)
var minutes = 0
var seconds = 9
var timeOverMsg = "<span style='color:#CC5B5B'>!<br/>!<br/>!<br/>!<br/>!<br/>!</span>"

// ##############  TAG SHORTCUT  ##############
var toggleTagsShortcut = "C";

// ENTER THE TAG TERM WHICH, WHEN PRESENT, WILL TRIGGER A RED BACKGROUND
var tagID = "XXXYYYZZZ"

// ############## USER CONFIGURATION END ##############
</script>



<script>
  var clozeOneByOneEnabled = true;
  try {
    clozeOneByOneEnabled = `{{One by one}}` !== ""
  } catch (exception) {
    console.log(exception)
  }
  
  window.clozeHints = [];
  if (clozeOneByOneEnabled) {
    // Save cloze hints to display in the back
    let clozes = document.getElementsByClassName("cloze")
    for(var i = 0; i < clozes.length; i++) {
      if (clozes[i].innerHTML === "[...]") {
        window.clozeHints.push("")
      } else {
        window.clozeHints.push(clozes[i].innerHTML)
      }
    }

    if(autoflip) {
      // avoid flickering. Must unset this in the back.
      document.getElementById("qa").style.display = "none";

      if (window.pycmd) {
        pycmd("ans")
      } else if (window.showAnswer) {
        showAnswer()
      }    
      // AnkiMobile JS API doesn't have one for show answer. 
      // Best alternative is to use Taps/Swipes to show answer.
    }
  }
</script>


<script>
  if (window.ankingEventListeners) {
    for (const listener of ankingEventListeners) {
      const type = listener[0]
      const handler = listener[1]
      document.removeEventListener(type, handler)
    }
  }
  window.ankingEventListeners = []
  
  window.ankingAddEventListener = function(type, handler) {
    document.addEventListener(type, handler)
    window.ankingEventListeners.push([type, handler])
  }
</script>


<script>
  var specialCharCodes = {
    "-": "minus",
    "=": "equal",
    "[": "bracketleft",
    "]": "bracketright",
    ";": "semicolon",
    "'": "quote",
    "`": "backquote",
    "\\": "backslash",
    ",": "comma",
    ".": "period",
    "/": "slash",
  };
  // Returns function that match keyboard event to see if it matches given shortcut.
  function shortcutMatcher(shortcut) {
    let shortcutKeys = shortcut.toLowerCase().split(/[+]/).map(key => key.trim())
    let mainKey = shortcutKeys[shortcutKeys.length - 1]
    if (mainKey.length === 1) {
      if (/\d/.test(mainKey)) {
        mainKey = "digit" + mainKey
      } else if (/[a-zA-Z]/.test(mainKey)) {
        mainKey = "key" + mainKey
      } else {
        let code = specialCharCodes[mainKey];
        if (code) {
          mainKey = code
        }
      }
    }
    let ctrl = shortcutKeys.includes("ctrl")
    let shift = shortcutKeys.includes("shift")
    let alt = shortcutKeys.includes("alt")

    let matchShortcut = function (ctrl, shift, alt, mainKey, event) {
      if (mainKey !== event.code.toLowerCase()) return false
      if (ctrl !== (event.ctrlKey || event.metaKey)) return false
      if (shift !== event.shiftKey) return false
      if (alt !== event.altKey) return false
      return true
    }.bind(window, ctrl, shift, alt, mainKey)
    
    return matchShortcut
  }
</script>


<div class="timer" id="s2"></div>
<script>
  function countdown(elementName, minutes, seconds) {
    var element, endTime, mins, msLeft, time;
    function twoDigits( n ) {
      return (n <= 9 ? "0" + n : n); 
    }
    function updateTimer() {
      msLeft = endTime - (+new Date);
      
      if ( msLeft < 1000 ) {
        element.innerHTML = timeOverMsg;
      } else {
        time = new Date( msLeft );
        mins = time.getUTCMinutes();
        element.innerHTML = mins + ':' + twoDigits(time.getUTCSeconds());
        setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
      }
    }
    element = document.getElementById(elementName);
    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
    updateTimer();
  }
  countdown("s2", minutes, seconds ); //2nd value is the minute, 3rd is the seconds
</script>



<a href="https://www.ankingmed.com"><img src="_AnKingRound.png" alt="The AnKing" id="pic"></a>


<script>
    //DONT FADE BETWEEN CARDS
	qFade=0; if (typeof anki !== 'undefined') anki.qFade=qFade;
</script>


{{#Tags}}
<div id="tags-container">{{clickable::Tags}}</div>
<script>
  var tagContainer = document.getElementById("tags-container")
  if (tagContainer.childElementCount == 0) {
    var tagList = tagContainer.innerHTML.split(" ");
    var kbdList = [];
    var newTagContent = document.createElement("div");

    for (var i = 0; i < tagList.length; i++) {
      var newTag = document.createElement("kbd");
      newTag.innerHTML = tagList[i];
      newTagContent.append(newTag)
    }
    tagContainer.innerHTML = newTagContent.innerHTML;
    tagContainer.style.cursor = "default";
  }
  if (tagContainer.innerHTML.indexOf(tagID) != -1) {
    tagContainer.style.backgroundColor = "rgba(251,11,11,.15)";
  }

  function showtags() {
    var tagContainerShortcut = document.getElementById("tags-container");

    if (tagContainerShortcut.style.display
      === "none") {
      tagContainerShortcut.style.display = "block";
    } else {
      tagContainerShortcut.style.display =
        "none";
    }
  }
  
  var isShortcut = shortcutMatcher(toggleTagsShortcut)
  ankingAddEventListener('keyup', function (e) {
      if (isShortcut(e)) {
          showtags();
      }
  });

</script>
{{/Tags}}

**Comment by RisingOrange** [comment]
It should work correctly now.
