### ISSUE TITLE
One by one field not showing up on cards

### ISSUE THREAD

**Issue by blueophtho** [AnKingMed/anking_notes_addon#11]
#### Problem description
Somewhat sporadically, the one by one field is not showing up in the browser at the bottom of my note. The fields will include text, extra, personal notes, and missed questions, but the one by one (and ankihub id) do not show up. If I close the browser and reopen, the one by one field will usually reappear. Starting Anki in safe mode makes both the one by one and ankihub id field show up, but I am not sure how to replicate the problem I am having since it occurs sporadically.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54 Qt5
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Is this still occuring on 2.1.56Qt6?

**Comment by blueophtho** [comment]
Yes, it is

**Comment by AnKingMed** [comment]
My suspicion is this is another addon. @RisingOrange do you have any idea why this would happen. Would AnkiHub be causing this?

**Comment by AnKingMed** [comment]
@blueophtho is this still happening? Sorry we didn’t get to it sooner

**Comment by blueophtho** [comment]
@AnKingMed I haven't noticed it, I think it's gone now. Thanks for following up.
