### ISSUE TITLE
Last version causing duplicate menu when changing profile

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/anking_notes_addon#12]
![image](https://user-images.githubusercontent.com/57678116/203196435-d6410f48-1721-4a68-96ad-81f01cd45494.png)

**Comment by AnKingMed** [comment]
@RisingOrange can you fix this? It must have been something in your last update

**Comment by RisingOrange** [comment]
@AnKingMed Sorry about that, the current release (which I just put on AnkiWeb) doesn't have this problem anymore.
