### ISSUE TITLE
Add new Sketchy-Cloze note type

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/anking_notes_addon#16]
@RisingOrange I just added the new Sketchy-Cloze note type. I think I did everything right on the other repo (probably best to check). Does anything need to be done on this side to make a new Sketchy-Cloze tab? 

I basically duplicated the Physeo-Cloze note type and then modified colors and a little bit of the templates, but no major changes. Should function like most of the Anking note types

**Comment by AnKingMed** [comment]
I had to build the note types to update the derm note type and it looks like the Sketchy note type just got pulled in so maybe everything is ok?

**Comment by RisingOrange** [comment]
@AnKingMed Yes, it looks like everything is working. The automatic tests are successful and I also did some manual testing.

**Comment by AnKingMed** [comment]
Awesome! Thanks for checking
