### ISSUE TITLE
If AnKingOverhaul doesn't exist, it won't recommend update for AnKingOverhaul (AnkiHub)

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/anking_notes_addon#18]
A user would have to "import" the AnKingOverhaul note type first before it will suggest updates to the AnkiHub version of the note type

**Comment by AnKingMed** [comment]
@RisingOrange I messaged you on slack about this but figured it'd be best to make an actual issue for it to track

**Comment by RisingOrange** [comment]
Fixed in https://github.com/AnKing-Memberships/anking_notes_addon/commit/ca61867b80726c78c9916e47bd213c1a92556dc7.

**Comment by AnKingMed** [comment]
Thanks :)
