### ISSUE TITLE
Occlusions not showing up on IO one by one cards when deck is shared

### ISSUE THREAD

**Issue by Youseals** [AnKingMed/anking_notes_addon#27]
`Ive created an anki deck created mainly with IO one by one cards and they work perfectly fine with me. But when i share the deck with my friends the images show up but with no occlusions (just the image without the yellow boxes). This problem happens with both IOS and windows users and the cards work fine with me. The deck was shared via sharesheet on ios and apkg on desktop.` Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.10.1##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by abdnh** [comment]
Related: https://github.com/AnKing-VIP/AnKing-Note-Types/issues/200

This will be fixed in the next release.
