### ISSUE TITLE
IO-one by one note type image aspect ratios get distorted on zooming in or out in the recent update of Anking note types.

### ISSUE THREAD

**Issue by QuietBasil** [AnKingMed/anking_notes_addon#28]
#### Problem description

Just after updating to the new anking note types addon, opening addon settings, applying changes, and restarting anki, and then starting to review my cards - I see that my IO one by one card images are distorted in aspect ratios. I cannot zoom in with picture clarity anymore. Previously these cards worked just fine and even zoom worked pretty well. I have attached a screen recording in a zip file.

Thanks
[Anki 2024-04-10 10-55-19.zip](https://github.com/AnKing-VIP/anking_notes_addon/files/14927636/Anki.2024-04-10.10-55-19.zip)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

```
 ⁨23.12.1 (1a1d4d54)⁩
```

#### Error message (if any)

No error messages

```

```

**Comment by CaptainDead** [comment]
I shared the old version of Anking note type addons, if u want to revert back to that so that you can get rid of this issue, u can use the file I shared and follow the steps - 

https://github.com/AnKing-VIP/AnKing-Note-Types/issues/178#issuecomment-2045955406

**Comment by QuietBasil** [comment]
thanks!
