### ISSUE TITLE
Anki crashes when updating note type

### ISSUE THREAD

**Issue by damronatron** [AnKingMed/anking_notes_addon#3]
when I opened anki I was prompted to update my anking note types because a new version was available. I hit update and then anki quit and I got this big nasty error (see attached). I am on version 2.1.49, when I turn off all addons but this one it still crashes, when I try in another profiles it still crashes.
[Anki error note types.docx](https://github.com/AnKingMed/anking_notes_addon/files/8028920/Anki.error.note.types.docx)

**Comment by RisingOrange** [comment]
Thanks for reporting! This should work correctly in the newest update.
