### ISSUE TITLE
New versions are available pop-up keeping popping up

### ISSUE THREAD

**Issue by dochypermoose** [AnKingMed/anking_notes_addon#31]
#### Problem description

New versions are available pop-up doesn't respect "No" choice. I made some edits to the Anking notetypes, it works well for me and I don't want to update right now. When the pop-up appeared, I selected "No" — the pop-up disappeared, until I closed and re-opened Anki. "OK, I'll select 'Remind me later'" ... same thing happens. What's the point of a "No" and "Remind me later" if the pop-up is just going to appear EVERY time I open Anki. I feel like "No" should equal "Don't remind me until the add-on updates again, and "Remind me later" should be "Sure, remind me the next time I close/open Anki"

![image](https://github.com/user-attachments/assets/af2c2d82-c699-4245-8f80-20f5a38237ed)

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

```
24.06.3
```

#### Error message (if any)

```
N/A
```

FYI, the template for Bug reports is out of date ... it still uses the old "2.1.##" version framework

**Comment by AnKingMed** [comment]
@abdnh I've heard this a few times. Any idea why it keeps asking? Related to AnkiHub?

**Comment by abdnh** [comment]
Pushed a potential fix. The update logic had a flaw. @RisingOrange let me know if you notice an issue here.

**Comment by RisingOrange** [comment]
@abdnh Thanks, I adjusted the logic a bit: https://github.com/AnKing-VIP/anking_notes_addon/commit/0d5ce844c82651cb54660f2764b2a0b2ca7ca03e
