### ISSUE TITLE
New cards created with AnKingOverhaul note type do not follow the colours dictated by the addon (ie. bold/underline text)

### ISSUE THREAD

**Issue by wiffleman** [AnKingMed/anking_notes_addon#5]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Creating new cards using the AnkingOverhaul Note Type does not generate cards using the style that is dictated in the Anking Notes Types addon - ie. I have a custom colour for BOLDED text; this is reflected in all the native AnKing cards; however, when I create new cards with bold text none of it is reflected in the new text colour - just comes out white.

Any idea why this is happening? Have ensured that I am using the right note types. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.50
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by RisingOrange** [comment]
Are you sure that the note type you are using is not named something like "AnKingOverhaul-#####" where ##### are some random characters?
